# gruvbox-material — cores da status bar (gerado a partir da paleta do tema nvim).
set -g status-style              "bg=#282828,fg=#d4be98"
set -g status-left               "#[fg=#282828,bg=#a9b665,bold] #S #[fg=#a9b665,bg=#282828] "
set -g window-status-format          "#[fg=#928374] #I:#W "
set -g window-status-current-format  "#[fg=#282828,bg=#ea6962,bold] #I:#W "
set -g status-right              "#[fg=#a9b665]saved #{continuum_status}m "
set -ag status-right             "#[fg=#45403d]│ #[fg=#d8a657]#h "
set -ag status-right             "#[fg=#45403d]│ #[fg=#d4be98]%Y-%m-%d %H:%M "
set -g pane-border-style         "fg=#45403d"
set -g pane-active-border-style  "fg=#a9b665"
set -g message-style             "bg=#282828,fg=#d8a657"
set -g message-command-style     "bg=#282828,fg=#d8a657"
set -g mode-style                "bg=#a9b665,fg=#282828"
