# iawriter — cores da status bar (gerado a partir da paleta do tema nvim).
set -g status-style              "bg=#f5f6f6,fg=#424242"
set -g status-left               "#[fg=#f5f6f6,bg=#117777,bold] #S #[fg=#117777,bg=#f5f6f6] "
set -g window-status-format          "#[fg=#000099] #I:#W "
set -g window-status-current-format  "#[fg=#f5f6f6,bg=#000000,bold] #I:#W "
set -g status-right              "#[fg=#b30000]saved #{continuum_status}m "
set -ag status-right             "#[fg=#ccccdd]│ #[fg=#338855]#h "
set -ag status-right             "#[fg=#ccccdd]│ #[fg=#424242]%Y-%m-%d %H:%M "
set -g pane-border-style         "fg=#ccccdd"
set -g pane-active-border-style  "fg=#117777"
set -g message-style             "bg=#f5f6f6,fg=#338855"
set -g message-command-style     "bg=#f5f6f6,fg=#338855"
set -g mode-style                "bg=#117777,fg=#f5f6f6"
