# ir_black — cores da status bar (gerado a partir da paleta do tema nvim).
set -g status-style              "bg=#000000,fg=#f6f3e8"
set -g status-left               "#[fg=#000000,bg=#ffd2a7,bold] #S #[fg=#ffd2a7,bg=#000000] "
set -g window-status-format          "#[fg=#7c7c7c] #I:#W "
set -g window-status-current-format  "#[fg=#000000,bg=#96cbfe,bold] #I:#W "
set -g status-right              "#[fg=#a8ff60]saved #{continuum_status}m "
set -ag status-right             "#[fg=#262d51]│ #[fg=#ffffb6]#h "
set -ag status-right             "#[fg=#262d51]│ #[fg=#f6f3e8]%Y-%m-%d %H:%M "
set -g pane-border-style         "fg=#262d51"
set -g pane-active-border-style  "fg=#ffd2a7"
set -g message-style             "bg=#000000,fg=#ffffb6"
set -g message-command-style     "bg=#000000,fg=#ffffb6"
set -g mode-style                "bg=#ffd2a7,fg=#000000"
