# matteblack — cores da status bar (gerado a partir da paleta do tema nvim).
set -g status-style              "bg=#121212,fg=#eaeaea"
set -g status-left               "#[fg=#121212,bg=#dc2626,bold] #S #[fg=#dc2626,bg=#121212] "
set -g window-status-format          "#[fg=#8a8a8d] #I:#W "
set -g window-status-current-format  "#[fg=#121212,bg=#059669,bold] #I:#W "
set -g status-right              "#[fg=#059669]saved #{continuum_status}m "
set -ag status-right             "#[fg=#333333]│ #[fg=#fbbf24]#h "
set -ag status-right             "#[fg=#333333]│ #[fg=#eaeaea]%Y-%m-%d %H:%M "
set -g pane-border-style         "fg=#333333"
set -g pane-active-border-style  "fg=#dc2626"
set -g message-style             "bg=#121212,fg=#fbbf24"
set -g message-command-style     "bg=#121212,fg=#fbbf24"
set -g mode-style                "bg=#dc2626,fg=#121212"
