# mirodark — cores da status bar (gerado a partir da paleta do tema nvim).
set -g status-style              "bg=#121212,fg=#c0c0c0"
set -g status-left               "#[fg=#121212,bg=#2b7694,bold] #S #[fg=#2b7694,bg=#121212] "
set -g window-status-format          "#[fg=#899ca1] #I:#W "
set -g window-status-current-format  "#[fg=#121212,bg=#cf4f88,bold] #I:#W "
set -g status-right              "#[fg=#287373]saved #{continuum_status}m "
set -ag status-right             "#[fg=#333333]│ #[fg=#bf85cc]#h "
set -ag status-right             "#[fg=#333333]│ #[fg=#c0c0c0]%Y-%m-%d %H:%M "
set -g pane-border-style         "fg=#333333"
set -g pane-active-border-style  "fg=#2b7694"
set -g message-style             "bg=#121212,fg=#bf85cc"
set -g message-command-style     "bg=#121212,fg=#bf85cc"
set -g mode-style                "bg=#2b7694,fg=#121212"
