# tairiki-dark — cores da status bar (gerado a partir da paleta do tema nvim).
set -g status-style              "bg=#151515,fg=#c5c8c6"
set -g status-left               "#[fg=#151515,bg=#81a2be,bold] #S #[fg=#81a2be,bg=#151515] "
set -g window-status-format          "#[fg=#a89984] #I:#W "
set -g window-status-current-format  "#[fg=#151515,bg=#b294bb,bold] #I:#W "
set -g status-right              "#[fg=#b5bd68]saved #{continuum_status}m "
set -ag status-right             "#[fg=#3b3f4c]│ #[fg=#f0c674]#h "
set -ag status-right             "#[fg=#3b3f4c]│ #[fg=#c5c8c6]%Y-%m-%d %H:%M "
set -g pane-border-style         "fg=#3b3f4c"
set -g pane-active-border-style  "fg=#81a2be"
set -g message-style             "bg=#151515,fg=#f0c674"
set -g message-command-style     "bg=#151515,fg=#f0c674"
set -g mode-style                "bg=#81a2be,fg=#151515"
