# unicon — cores da status bar (gerado a partir da paleta do tema nvim).
set -g status-style              "bg=#111111,fg=#b9b9b9"
set -g status-left               "#[fg=#111111,bg=#8cf8f7,bold] #S #[fg=#8cf8f7,bg=#111111] "
set -g window-status-format          "#[fg=#6a6a6a] #I:#W "
set -g window-status-current-format  "#[fg=#111111,bg=#748be8,bold] #I:#W "
set -g status-right              "#[fg=#96944b]saved #{continuum_status}m "
set -ag status-right             "#[fg=#3b3b3b]│ #[fg=#c28161]#h "
set -ag status-right             "#[fg=#3b3b3b]│ #[fg=#b9b9b9]%Y-%m-%d %H:%M "
set -g pane-border-style         "fg=#3b3b3b"
set -g pane-active-border-style  "fg=#8cf8f7"
set -g message-style             "bg=#111111,fg=#c28161"
set -g message-command-style     "bg=#111111,fg=#c28161"
set -g mode-style                "bg=#8cf8f7,fg=#111111"
