# zenbones — cores da status bar (gerado a partir da paleta do tema nvim).
set -g status-style              "bg=#1c1917,fg=#b4bdc3"
set -g status-left               "#[fg=#1c1917,bg=#a1938c,bold] #S #[fg=#a1938c,bg=#1c1917] "
set -g window-status-format          "#[fg=#6e6763] #I:#W "
set -g window-status-current-format  "#[fg=#1c1917,bg=#868c91,bold] #I:#W "
set -g status-right              "#[fg=#868c91]saved #{continuum_status}m "
set -ag status-right             "#[fg=#3d4042]│ #[fg=#a1938c]#h "
set -ag status-right             "#[fg=#3d4042]│ #[fg=#b4bdc3]%Y-%m-%d %H:%M "
set -g pane-border-style         "fg=#3d4042"
set -g pane-active-border-style  "fg=#a1938c"
set -g message-style             "bg=#1c1917,fg=#a1938c"
set -g message-command-style     "bg=#1c1917,fg=#a1938c"
set -g mode-style                "bg=#a1938c,fg=#1c1917"
