# Flexoki Dark — https://stephango.com/flexoki

foreground              #CECDC3
background              #100F0F
selection_foreground    #100F0F
selection_background    #CECDC3
cursor                  #CECDC3
cursor_text_color       #100F0F

url_color               #4385BE

# Black
color0  #1C1B1A
color8  #575653

# Red
color1  #AF3029
color9  #D14D41

# Green
color2  #66800B
color10 #879A39

# Yellow
color3  #AD8301
color11 #D0A215

# Blue
color4  #205EA6
color12 #4385BE

# Magenta
color5  #A02F6F
color13 #CE5D97

# Cyan
color6  #24837B
color14 #3AA99F

# White
color7  #CECDC3
color15 #FFFCF0
